### ISSUE TITLE
PipingBag ControllerFactoryFilter invalidates template paths

### ISSUE THREAD

**Issue by aydot** [lorenzo/piping-bag#11]
in my app.php, my paths is set up like:

```
'App' => [
    'paths' => [
        'plugins' => [ROOT . DS . 'plugins' . DS],
        'templates' => [
            APP . 'Template' . DS,
            APP . 'Template' . DS . 'UserMgt' . DS 
        ],
        'locales' => [APP . 'Locale' . DS],
    ]
],
```

My Users template is located at 
template\UserMgt\Users\index
template\UserMgt\Users\view
when i added 

```
DispatcherFactory::add('PipingBag\Routing\Filter\ControllerFactoryFilter');
```

or

```
use PipingBag\Di\PipingBag;
DispatcherFactory::add('PipingBag\Routing\Filter\ControllerFactoryFilter');
```

to my bootstrap, and try to navigate to localhost\users\index from my browser,  I get 

```
[Semantical Error] The annotation "@Inject" in method App\Controller\UsersController::index() was never imported. 
Did you maybe forget to add a "use" statement for this annotation? 
Doctrine\Common\Annotations\AnnotationException
```

I get this error even though I am not injecting anything inside my UsersController. my UsersController has just the basic bake crud code.

Also if i have another template located at template\UserMgt\UserRegistration\index.ctp,
cake cant locate the index page when i add your pipingbag controller factory filter to my bootsrap. it either shows a blank page or I get a MissingTemplateException. 
when i comment out the line, the index page works fine.

**Comment by lorenzo** [comment]
This sounds like a caching problem, try to remove the cache files in your tmp/cache folder

**Comment by aydot** [comment]
I cleared my cache. The first error 'annotation....' is gone. I am still getting a MissingTemplateException though.

**Comment by lorenzo** [comment]
Are you using the code from cakepph 3 master branch? I'm waiting for the 3.0.3 release of the framework to mark a stable version of this plugin, as it is currently depending on some changes that are still not tagged.

**Comment by aydot** [comment]
```
"cakephp/cakephp": "~3.0"
```

**Comment by aydot** [comment]
Is there a roadmap somewhere? I can switch to master branch and test the plugin if you'd like? Or we can just wait till 3.0.3 is out.

**Comment by lorenzo** [comment]
3.0.3 should be out really soon, Please test using the master branch and report if that fixes it for you

**Comment by lorenzo** [comment]
3.0.3 was just released, you can try with this new release and confirm that this is working as it should

**Comment by aydot** [comment]
it is working. thank you!

**Comment by lorenzo** [comment]
yay!

**Comment by aydot** [comment]
just to let you know i am getting the [Semantical Error] The annotation "@Inject"... error again

**Comment by lorenzo** [comment]
Delete the cache. I'm thinking of a solution where the cache is not as annoying as it is right now
