### ISSUE TITLE
Bad type hinting on PipingBag::get()

### ISSUE THREAD

**Issue by btaens** [lorenzo/piping-bag#13]
Hello,
The phpdocs have an error on PipingBag::get().

``` php
/**
     * Return an instance of a class after resolving its dependencies.
     *
     * @param $class The class name or interface name to load.
     * @param $name The alias given to this class for namespacing the configuration.
     * @return mixed
     */
    public static function get($class, $name = Name::ANY)
    {
    }
```

`@param $class` and `@param $name` should both be `@param string $class` and `@param string $name`. My IDE is looking for a `The` class, which does not exist, obviously.

**Comment by lorenzo** [comment]
Would you like to submit a pull request for this?

**Comment by btaens** [comment]
Sure, though I might only be able to do so in a few days, if that's fine.
