### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by brunoserrar** [lorenzo/piping-bag#19]
Hi! I'm trying to use the plugin but i'm getting this error:

`{
    "success": false,
    "data": {
        "message": "dependency 'App\\Controller\\HttpClientInterface' with name '' used in /Users/brunoserra/Sites/EventsPlatform/src/Controller/EventsController.php:29 ($connection)",
        "url": "/events/set-http-client",
        "code": 500,
        "file": "/Users/brunoserra/Sites/EventsPlatform/vendor/ray/di/src/Arguments.php",
        "line": 63
    }
}`

I did exactly what the docs suggests. How can I solve it?
Thanks in advence

**Comment by lorenzo** [comment]
I don'r recondite that logging format. Where is this coming from? how can I reproduce this issue?

**Comment by brunoserrar** [comment]
Thanks for replying @lorenzo! I've solved the issue by deleting the cake_pipingbag_instance cache file. Now It's working perfectly.

I have just a simple question now, how can I use different classes that implements the same interface? That's not really clear to me :(

Thanks by the awesome plugin, by the way!

**Comment by lorenzo** [comment]
You can do that by using the `@Named` annotation. This annotation lets you specify what specific implementation gets injected to a method, based on an arbitrary label:

https://github.com/ray-di/Ray.Di#named

There are many other ways, but this one is by far the easiest.

**Comment by brunoserrar** [comment]
That's awesome! Thank you for helping me 😄
