### ISSUE TITLE
Fatal error on Cake 3.3

### ISSUE THREAD

**Issue by viraj-khatavkar** [lorenzo/piping-bag#20]
@lorenzo I installed the component but I'm getting a fatal error as mentioned in the figure attached to the issue. 

![screenshot-local harborcompliance com-2017-09-19-11-10-24-593](https://user-images.githubusercontent.com/5693836/30577378-71f6fb12-9d2b-11e7-9c3e-2608b156d67b.png)

**Comment by lorenzo** [comment]
Piping bag uses a cache to speedup the annotations reading process. Please clear the cache and try again

**Comment by viraj-khatavkar** [comment]
It works now. Thanks a lot for creating this package.
