### ISSUE TITLE
Example for constructor injection in Controller class

### ISSUE THREAD

**Issue by steffenbrand** [lorenzo/piping-bag#22]
Could you provide an example in the readme? Thanks in advance :)

**Comment by lorenzo** [comment]
CakePHP controllers already get their own arguments, so injecting extra stuff in them is challenging and often doe snot look good. For controllers I recommend using the `@Assisted` annotation or use setter injection.

Does this answer your question?

**Comment by steffenbrand** [comment]
Yes, I think setter injection will do.

I was just asking because Ray.DI does support constructor injection and I am used to doing it that way.
