### ISSUE TITLE
lorenzo/piping-bag dev-master requires ray/di dev-compiler

### ISSUE THREAD

**Issue by btaens** [lorenzo/piping-bag#9]
The composer.json seems to require "ray/di": "dev-compiler", which cannot be found.
I think it's supposed to be dev-master.

**Comment by lorenzo** [comment]
I'm currently using a dev branch for a fork, because eI need a feature from there. Is that not working correctly for you?

**Comment by lorenzo** [comment]
Ah, I just realized that the feature I wanted was marked as stable now :D

**Comment by lorenzo** [comment]
Fixed... Please note that the master branch of this repository currently depends on cakephp master. I will tag a new stable version once CakePHP 3.0.3 is released
